version: "3"
services:
  node-dev:
    build:
      context: .
      dockerfile: ./dev/Dockerfile.node
      args:
        - NODE_VERSION=20.10.0
        - WORKDIR=${PWD}
    tty: true
    develop:
      watch:
        - action: sync
          path: .
          target: ${PWD}
        - action: rebuild
          path: pnpm-lock.yaml
  ts-postgres-template:
    image: postgres:16
    ports:
      - 35432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  ts-fastify-template:
    build:
      context: .
      dockerfile: ./dev/Dockerfile.node
      args:
        - NODE_VERSION=20.10.0
        - WORKDIR=${PWD}
    command: pnpm --filter "@puyogg/ts-fastify-template" start:dev
    depends_on:
      ts-postgres-template:
        condition: service_healthy
    environment:
      - FASTIFY_HOST=0.0.0.0
      - POSTGRES_HOST=ts-postgres-template
      - POSTGRES_HOST_TEST=ts-postgres-template-test
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_DBNAME=db
      - POSTGRES_PASSWORD=password
    ports:
      - 3000:3000 # api
      - 9229:9229 # api debug
      - 9230:9230 # test debug
    develop:
      watch:
        - action: sync
          path: .
          target: ${PWD}
        - action: rebuild
          path: pnpm-lock.yaml
  puyoquest-db:
    image: postgres:16
    ports:
      - 35433:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ppqdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - puyoquest-db-volume:/var/lib/postgresql/data
  puyoquest-api:
    build:
      context: .
      dockerfile: ./dev/Dockerfile.node
      args:
        - NODE_VERSION=20.10.0
        - WORKDIR=${PWD}
  yotarou:
    build:
      context: .
      dockerfile: ./dev/Dockerfile.node
      args:
        - NODE_VERSION=20.10.0
        - WORKDIR=${PWD}
    command: pnpm --filter "@puyogg/yotarou" start:dev
    # depends_on:

volumes:
  ts-postgres-template-volume:
  puyoquest-db-volume:
