version: "3"
services:
  ts-postgres-template:
    image: postgres:16
    ports:
      - 35432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - ts-postgres-template-volume:/var/lib/postgresql/data

  ts-postgres-template-test:
    image: postgres:16
    ports:
      - 35434:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db

  puyoquest-db:
    image: postgres:16
    ports:
      - 35433:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - puyoquest-db-volume:/var/lib/postgresql/data

volumes:
  ts-postgres-template-volume:
  puyoquest-db-volume:
