name: Setup Doker Deployment

description: Log into AWS, log Docker into AWS ECR, and setup Docker layer caches.

inputs:
  AWS_ACCOUNT_ID:
    description: AWS Account ID
    required: true

outputs:
  GIT_SHA7:
    description: 7 character SHA of the current commit
    value: ${{ steps.sha_short.outputs.SHA_SHORT }}

runs:
  using: composite
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ inputs.AWS_ACCOUNT_ID }}:role/GitHubActionsAwsOIDCConnect
        aws-region: us-east-1
    - name: Login to AWS ECR
      id: login_ecr
      uses: aws-actions/amazon-ecr-login@v2
    - name: Set up Docker Context for Buildx
      shell: bash
      run: docker context create builders
    - uses: docker/setup-buildx-action@v3
      with:
        endpoint: builders
    - name: Load monorepo node image in Docker layer cache
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        file: ./dev/Dockerfile.node
        tags: puyogg-node:latest
        target: ci
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          NODE_VERSION=20.10.0
          WORKDIR=/app
    - name: Set 7 character SHA
      id: sha_short
      shell: bash
      run: echo "SHA_SHORT=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT
