name: Deploy

on:
  workflow_call:
    inputs:
      packages:
        required: true
        type: string
        description: stringified JSON array
  workflow_dispatch:
    inputs:
      packages:
        required: false
        type: string
        description: stringified JSON array
        default: >
          [
            "@puyogg/puyoquest-api"
          ]

permissions:
  id-token: write
  contents: read

jobs:
  # test_mergeability:
  #   name: Test Mergeability
  #   uses: ./.github/workflows/test.yml
  #   secrets: inherit

  deploy_infrastructure:
    name: Deploy Infrastructure
    # needs: test_mergeability
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID_DEV }}:role/PulumiRole
          aws-region: us-east-1
      - uses: ./.github/actions/setup-node-cache-build
      - uses: pulumi/actions@v4
        with:
          command: up
          stack-name: puyogg/infrastructure/dev
          work-dir: ./infrastructure/entrypoint
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

  get_docker_image_packages:
    name: Get Packages with Docker Images
    needs: deploy_infrastructure
    runs-on: ubuntu-latest
    outputs:
      PACKAGES: ${{ steps.buildable_packages.outputs.PACKAGES }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-cache-build
      - id: buildable_packages
        run: echo "PACKAGES=$(node scripts/get-docker-images.js '${{ inputs.packages }}')" >> "$GITHUB_OUTPUT"

  puyoquest-api:
    needs: get_docker_image_packages
    if: ${{ contains(fromJSON(needs.get_docker_image_packages.outputs.PACKAGES), '@puyogg/puyoquest-api') }}
    uses: ./.github/workflows/deploy-puyoquest-api.yml
    secrets: inherit
