name: Release

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish and Version to GitHub Packages Registry
    runs-on: ubuntu-latest
    outputs:
      PUBLISHED: ${{ steps.changesets.outputs.published }}
      PUBLISHED_PACKAGES: ${{ steps.changesets.outputs.publishedPackages }}
      PUBLISHED_PACKAGE_NAMES: ${{ steps.mapped_package_names.outputs.PUBLISHED_PACKAGE_NAMES }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-cache-build
      - name: Create Release PR or Publish+Deploy
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm ci:version
          commit: "chore: update versions"
          title: "Release: update versions"
          publish: pnpm ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "PUBLISHED ${{ steps.changesets.outputs.published }}"
      - run: echo "PUBLISHED PACKAGES ARRAY ${{ steps.changesets.outputs.publishedPackages }}"
      - id: mapped_package_names
        run: echo "PUBLISHED_PACKAGE_NAMES=$(node scripts/map-package-name.js '${{ steps.changesets.outputs.publishedPackages }}')" >> $GITHUB_OUTPUT

  deploy:
    needs: publish
    if: needs.publish.outputs.PUBLISHED == 'true'
    uses: ./.github/workflows/deploy.yml
    with:
      packages: ${{ needs.publish.outputs.PUBLISHED_PACKAGE_NAMES }}
    secrets: inherit
