name: Test

on:
  workflow_call:

permissions:
  id-token: write
  contents: read

env:
  NODE_VERSION: 20

jobs:
  js_build:
    name: (JS) Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-cache-build

  js_lint:
    name: (JS) Format & Lint
    runs-on: ubuntu-latest
    needs: js_build
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-cache-build
      - run: pnpm -r format-check
      - run: pnpm -r lint

  js_unit_test:
    name: (JS) Unit Test
    runs-on: ubuntu-latest
    needs: js_build
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-cache-build
      - run: pnpm -r unit-test

  docker_build:
    name: Build & Cache Docker Images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          file: ./dev/Dockerfile.node
          tags: puyogg-node:latest
          target: ci
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            NODE_VERSION=20.10.0
            WORKDIR=/app

  integration_test:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: docker_build
    strategy:
      matrix:
        package:
          - puyoquest-db
          - ts-postgres-template
          - ts-fastify-template
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          file: ./dev/Dockerfile.node
          tags: puyogg-node:latest
          target: ci
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            NODE_VERSION=20.10.0
            WORKDIR=/app
      - run: ./scripts/init-env.sh
      - run: |
          pnpm --filter @puyogg/${{ matrix.package }} int-test:ci
          docker compose down
