name: Setup Docker Testing

description: Setup Docker layer caches for integration tests

inputs:
  AWS_ACCOUNT_ID:
    description: AWS Account ID
    required: true

runs:
  using: composite
  steps:
    - name: Set up Docker Context for Buildx
      shell: bash
      run: docker context create builders
    - uses: docker/setup-buildx-action@v3
      with:
        endpoint: builders
    # - name: Load monorepo node image in Docker layer cache
    #   uses: docker/build-push-action@v5
    #   with:
    #     context: .
    #     push: false
    #     file: ./dev/Dockerfile.node
    #     tags: puyogg-node:latest
    #     target: ci
    #     cache-from: type=gha
    #     cache-to: type=gha,mode=max
    #     build-args: |
    #       NODE_VERSION=20.10.0
    #       WORKDIR=/app
    #     load: true
